- name: create ec2_instance
  hosts: localhost
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: t2.micro
      name: "{{ item }}"
      security_group: launch-wizard-1
      image_id: ami-090252cbe067a9e58
      key_name: no
      tags:
        Name: "{{ item }}"
    loop:
    - db
    - backend
    - frontend
